<?php
bolt_decrypt( __FILE__ , 'FNB7KG'); return 0;
##!!!##qakNAAwEEg8AAgS/4A8P++wOAwQLEvvnEdqpqRQSBL/oCwsUDAgNABME++MAEwABABIE++QLDhAUBA0T++wOAwQL2qmpAgsAEhK/6wQTEwQREr8EFxMEDQMSv+wOAwQLqRqpv7+/vw8RDhMEAhMEA7/DEwABCwS/3L/GBxH+CwQTEwQRxtqpqb+/v78PFAELCAK/wxMIDAQSEwAMDxK/3L8FAAsSBNqpHKk=