<?php
bolt_decrypt( __FILE__ , '9bhgdg'); return 0;
##!!!##Pz+jlqKaqKWWmJpVdqWlkYKkmZqhqJF9p3A/P6qomlV+oaGqop6jlqmakXmWqZaXlqiakXqhpKaqmqOpkYKkmZqhcD8/mKGWqKhViJahlqeudpmZeZqZqpipVZqtqZqjmahVgqSZmqE/sD9VVVVVpaekqZqYqZqZVVmplpehmlVyVVydp5SolqGWp66UlpmZlJmamaqYqVxwPz9VVVVVpaekqZqYqZqZVVmcqpanmZqZVXJVkJJwP1VVVVWlqpehnphVWameopqoqZaipahVclWblqGomnA/VVVVVT+yPw==