<?php
bolt_decrypt( __FILE__ , 'L6RDAN'); return 0;
##!!!##sbEVCBQMGhcICgzH6BcXA/QWCwwTGgPvGeKxsRwaDMfwExMcFBAVCBsMA+sIGwgJCBoMA+wTFhgcDBUbA/QWCwwT4rGxChMIGhrH+hsIGxwa+xkIChIMGccMHxsMFQsax/QWCwwTsSKxsBcZFhsMChsMC8fLGwgJEwzH5MfJDxkGCBoaFgoQCBsMBhobCBscGgYbGQgKEgwZyeKxscfHx8cXHAkTEArHyxsQFAwaGwgUFxrH5McNCBMaDOLHsSSx