<?php
bolt_decrypt( __FILE__ , 'VQJ9HE'); return 0;
##!!!##wcElGCQcKicYGhzX+CcnEwQmGxwjKhP/KfLBwSwqHNcAIyMsJCAlGCscE/sYKxgZGCocE/wjJigsHCUrEwQmGxwj8sHBGiMYKirXDiYpIhwp1xwvKxwlGyrXBCYbHCPBMsHX19fXJykmKxwaKxwb19srGBkjHPTX2R8pFi4mKSIcKRYpHBopLCArJBwlK9nywdfX19cnLBkjIBrX2ysgJBwqKxgkJyr01x0YIyoc8tfBNME=