<?php
bolt_decrypt( __FILE__ , 'RIi560'); return 0;
##!!!##qakNAAwEEg8AAgS/4A8P++wOAwQLEtqpqRQSBL/oCwsUDAgNABME++MAEwABABIE++QLDhAUBA0T++wOAwQL2qkUEgS/4+HaqakCCwASEr/0EgQR6w4GvwQXEwQNAxK/7A4DBAupGqmpqA8RDhMEAhMEA7/DEwABCwS/3L/GFBIEEf4LDgYSxtqpv7+/vw8RDhMEAhMEA7/DBhQAEQMEA7/cv/rGCAPG/Nqpqb+/v78PEQ4TBAITBAO/wwMAEwQSv9y/+qm/v7+/v7+/v8YCEQQAEwQD/gATxsvGFA8DABMEA/4AE8apv7+/v/zaqakcqQ==